#!/usr/bin/env bash
#
# update-pins.sh — regenerate the size + SHA-256 integrity pins for a release.
#
# The launcher (plugins/circleci-yaml-lsp/bin/circleci-yaml-lsp) pins the byte
# size and SHA-256 of each platform binary so a corrupt or tampered download is
# refused. Those pins MUST be regenerated whenever the pinned VERSION changes.
#
# Usage:
#   scripts/update-pins.sh [VERSION] [--write]
#     # VERSION defaults to the VERSION in the launcher.
#     # --write rewrites the launcher pin block in place (between the
#     #   "# <generated:pins>" / "# </generated:pins>" markers); without it the
#     #   `case` arms are printed to stderr for manual pasting.
#
# It downloads each platform asset for VERSION and either prints the bash `case`
# arms or splices them into the launcher. Remember to ALSO bump "version" in
# plugin.json — Claude Code applies plugin updates only when that string changes.
#
set -euo pipefail

REPO="CircleCI-Public/circleci-yaml-language-server"
launcher="$(cd "$(dirname "$0")/.." && pwd)/plugins/circleci-yaml-lsp/bin/circleci-yaml-lsp"

# Parse args: an optional VERSION (first non-flag arg) and an optional --write flag, any order.
WRITE=0
VERSION=""
for arg in "$@"; do
  case "$arg" in
    --write) WRITE=1 ;;
    *) if [ -z "$VERSION" ]; then VERSION="$arg"; fi ;;
  esac
done
VERSION="${VERSION:-$(grep -E '^VERSION=' "$launcher" | head -1 | cut -d'"' -f2)}"

echo "# integrity pins for $REPO @ $VERSION" >&2
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT

arms=""
for a in darwin-arm64-lsp darwin-amd64-lsp linux-amd64-lsp linux-arm64-lsp; do
  url="https://github.com/$REPO/releases/download/$VERSION/$a"
  curl -fsSL "$url" -o "$tmp/$a"
  size="$(wc -c < "$tmp/$a" | tr -d ' ')"
  if command -v sha256sum >/dev/null 2>&1; then
    sha="$(sha256sum "$tmp/$a" | awk '{print $1}')"
  else
    sha="$(shasum -a 256 "$tmp/$a" | awk '{print $1}')"
  fi
  arms="$arms$(printf '    %-18s expected_size=%s; expected_sha="%s" ;;\n' "$a)" "$size" "$sha")
"
done
arms="$arms    *) expected_size=0; expected_sha=\"\" ;;"

if [ "$WRITE" -eq 1 ]; then
  node - "$launcher" "$arms" <<'NODE'
const fs = require("fs");
const [file, arms] = process.argv.slice(2);
const src = fs.readFileSync(file, "utf8");
const B = "# <generated:pins>", E = "# </generated:pins>";
const b = src.indexOf(B), e = src.indexOf(E);
if (b === -1 || e === -1) { console.error("pin markers not found"); process.exit(1); }
const head = src.slice(0, b);   // up to (not incl.) the open marker — keeps its 2-space indent
const tail = src.slice(e);      // from the close marker onward
// Trailing "  " re-indents the close marker (tail) to 2 spaces, matching the launcher.
const block = `${B} — regenerated by scripts/update-pins.sh --write; do not edit by hand.\n  case "$asset" in\n${arms}\n  esac\n  `;
fs.writeFileSync(file, head + block + tail);
console.error("updated pins in " + file);
NODE
else
  printf '%s\n' "$arms" >&2
fi

# Regenerate the schema-derived hover docs for this same VERSION so they stay in
# lockstep with the pinned server. (Edits lsp-hover.mjs in place; review the diff.)
echo "# regenerating hover docs for $VERSION" >&2
node "$(cd "$(dirname "$0")/.." && pwd)/scripts/gen-hover-docs.mjs"
